on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Run Setup script
      run: ./scripts/setup.sh
    - name: iOS Build Action
      # You may pin to the exact commit or the version.
      # uses: yukiarrr/ios-build-action@3d8ff63d40bce5dfd0ff8d1dda6ce543bf4c605a
      uses: yukiarrr/ios-build-action@v1.5.0
      with:
        # Project path
        project-path: Zotero.xcodeproj
        # For example, iOS Distribution
        code-signing-identity: iOS Distribution
        # Team id
        team-id: exampleteam
